### ISSUE TITLE
M3DBCluster spec documentation

### ISSUE THREAD

**Issue by mstump** [m3db/m3db-operator#105]
No documentation exists for the M3DBCluster YAML spec. Docs should be updated to include:
- Required and optional field 
- Valid ranges for fields

An example of a recent UX problem caused by the lack of docs had to do with my own experience setting up the operator. Our scratch cluster is in the central zone using 1 AZ. Rather than edit the ```isolationGroups``` fields I commented it out because in the rest of k8s taints/toleration are typically optional constructs. After submitting the manifest no cluster was created,  no events were present on the CRD, and no error messages were present in the operator logs. It took a fair bit of trial and error to discover that the cluster wouldn't be created until I updated ```isolationGroups``` to contain a single entry of 3 nodes.

**Comment by schallert** [comment]
Hey @mstump, thanks for the feedback. The auto-generated API docs currently enumerate the fields of the cluster spec: https://operator.m3db.io/api/#clusterspec, but I definitely agree we should do a better job of covering the valid ranges, as well as higher-level "what's valid" vs. not compared to what fields are just listed.

Btw we have ongoing work to make RF=3 clusters across a single zone: https://github.com/m3db/m3db-operator/pull/104

Once that feature makes it into a release (next week or two) we'll include better docs around controlling cluster topologies.

Would love to hear any other feedback you have, and we'll use this issue to track some of the docs I mentioned above.

**Comment by schallert** [comment]
Also I just realized the `required` column of those docs aren't totally correct, I'll see what we can do about better generating those.
