### ISSUE TITLE
etcd configuration doesn't work

### ISSUE THREAD

**Issue by brndnmtthws** [m3db/m3db-operator#138]
I set the `etcdEndpoints` value in the spec, however it does not get templated correctly in the configmap. I resorted to specifying a custom configmap instead as a workaround.

**Comment by schallert** [comment]
@brndnmtthws can you try again with the latest release, 0.2.0? The etcd changes were on master but not a tagged release for a while.

**Comment by brndnmtthws** [comment]
I've moved on to other things, but I may revisit m3db at a later time. I opened the issue so you know about it :)

**Comment by schallert** [comment]
Hope we can get you back some time! Closing out the issue due to likely being solved by new release.
