### ISSUE TITLE
Provide a YAML version of the CRD

### ISSUE THREAD

**Issue by schallert** [m3db/m3db-operator#153]
We currently install the CRD from within the operator. We should let people install it manually if they choose (also allows introspection of the spec).

**Comment by anandsinghkunwar** [comment]
Is there some place in the repository I can find this today?

**Comment by pickfire** [comment]
No, their CRD is still unstable and it is not there yet, so right now we still need to deploy it first, and wait for the other resources to fail, then deploy it again.

**Comment by pickfire** [comment]
Why is this closed?

**Comment by gibbscullen** [comment]
Part of clean up effort to close stale issues. If still an issue, feel free to start a discussion in the M3 slack for more community engagement. https://bit.ly/m3slack
