### ISSUE TITLE
Image Pull Secrets

### ISSUE THREAD

**Issue by araigneeman** [m3db/m3db-operator#159]
* What version of the operator are you running? Please include the docker tag. If using `master`, please include the git
  SHA logged when the operator first starts.

Version 0.2.0 with Helm charts

* What version of Kubernetes are you running? Please include the output of `kubectl version`.

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

* What are you trying to do?
Operator is installed successfully, but now i'm trying to create a cluster.
My docker registry is private, i need to pull a docker secret for Kubernetes to be able to pull the M3DBNode image as i already do for all others regular pods

* What did you expect to happen?

M3DBNode pods to be created

* What happened?
I didn't see any way to specify either a specific service account to pull the image or an "ImagePullSecrets" entry in the M3DBCluster API specification. This would be very helpful with private registries.

Right now Kubernetes can't pull the M3DBNode image (status "ImagePullBackOff")

**Comment by araigneeman** [comment]
I defined a pull policy on the default SA it works but it would still be a good idea to add those options on the M3DBCluster specification

**Comment by schallert** [comment]
This seems reasonable, will take a look!
