### ISSUE TITLE
Missing "patch" permission

### ISSUE THREAD

**Issue by bai** [m3db/m3db-operator#168]
* What version of the operator are you running?

`master` at `3d43802a616096f221847026474839f95704139a`.

* What version of Kubernetes are you running? Please include the output of `kubectl version`.

`1.13.7-gke.19`

* What happened?

With https://github.com/m3db/m3db-operator/pull/162 m3db-operator tries to patch pods, which requires additional permissions. Currently `patch` is not on the permissions list.

**Comment by schallert** [comment]
Fixed in #169
