### ISSUE TITLE
Error: Failed to update schema registry

### ISSUE THREAD

**Issue by cirego** [m3db/m3db-operator#172]
I'm  getting the following error while successfully bootstrapping the M3DB database. Is this benign or should I be worried? Is this an issue with the operator or should I file this under the M3DB project?

`
{"level":"error","ts":1566603044.810578,"msg":"failed to update schema registry","error":"can not update namespace(default) schema to empty","errorCauses":[{"error":"can not update namespace(default) schema to empty"}]}
`

**Comment by atlasW** [comment]
@cirego    have You solved the problem yet？  i have the same problem.

**Comment by cirego** [comment]
@atlasW: No, I have not solved the problem and I have stopped used m3db.

**Comment by kingmorning** [comment]
I have the same problem, who knows why?

**Comment by lz006** [comment]
same here

**Comment by khurshidatcadre** [comment]
+1

**Comment by cirego** [comment]
I have not solved this problem and I abandoned using m3db a long time ago. Going to close this issue as stale, given the lack of response from the m3db team.
