### ISSUE TITLE
Chart repository on S3 is no longer readable

### ISSUE THREAD

**Issue by theothermike** [m3db/m3db-operator#175]
trying to install the m3db-operator, all of a sudden in the last 1 hour or so, the S3 bucket that stores the chart is no longer readable

https://s3.amazonaws.com/m3-helm-charts-repository/stable

produces

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>CA34E35B60FF9A90</RequestId>
<HostId>
WRIprkOAj+iWcMZwji6zwkA2QQOyA2LOfAhb6pchG9uS9LcC40bxM9XjKIqMpEBPRM9YWEWrwZA=
</HostId>
</Error>
```

**Comment by schallert** [comment]
Hey @theothermike, sorry for the disruption. I believe Uber changed the permissions on the S3 bucket. I'm reaching out to some folks to see if we can get this reversed, and if not we can try to host the charts from a new location.

cc @mway

**Comment by jgagnon1** [comment]
Any update on this ? Seems like the permissions are still broken and unable to use m3db operator.

**Comment by schallert** [comment]
Hey folks, thanks for your patience here. We're working through some final permissions issues to merge the PR, but you can begin using the new public helm repo. We're hosting it out of a separately owned public GCS bucket now as opposed to Uber's now-private S3 bucket.

```
helm repo add m3db https://m3-helm-charts.storage.googleapis.com/stable
```

So far only 0.2.0 is published, we'll go back and publish the last 2 patch versions of 0.1.x as well. Please let us know if you run into any issues.
