### ISSUE TITLE
operator should only pull the namespace where the operator is in

### ISSUE THREAD

**Issue by yuecong** [m3db/m3db-operator#204]
Thanks for opening an issue for the M3DB Operator! We'd love to help you, but we need the following information included
with any issue:

* What version of the operator are you running? Please include the docker tag. If using `master`, please include the git
0.5.0

* What version of Kubernetes are you running? Please include the output of `kubectl version`.
1.12
* What are you trying to do?
Now the operator is watching all the namespaces for sts and pods. This can be quite slow and also many unnecessary API calls to the API server. e.g. it slows down to patch the pod-identity annotation to each pod. In one of my prod environment, I saw it takes more than 2- 5 minutes to just go through the logic for each pod and added annotations for pod-identity.

* What did you expect to happen?
It should only watch the namespace where the operator is in. I am ok the default behavior to monitor all, but I would like have one option to only monitor specific namespace.

* What happened?
The operator is monitoring all the namespaces and slows down its watch as well as too many unnecessary calls to  k8s api server in a large k8s environment. 

The fix would be very easy, and I already tested in my env. 
It is to change here 
https://github.com/m3db/m3db-operator/blob/master/cmd/m3db-operator/main.go#L171
https://github.com/m3db/m3db-operator/blob/master/cmd/m3db-operator/main.go#L173

to
```
kubeInformerFactory := kubeinformers.NewSharedInformerFactoryWithOptions(kubeClient, _informerSyncDuration,kubeinformers.WithNamespace("m3"))

m3dbClusterInformerFactory := informers.NewSharedInformerFactoryWithOptions(crdClient, _informerSyncDuration, informers.WithNamespace("m3"))
```
@schallert if you agree, I would have one PR to add this feature. Basically, I will add one more cmd option so that users can specify whether to monitor all namespaces or just one specific namespace.
By doing this, I can see it is really fast to bootstrap a new m3db cluster.

**Comment by schallert** [comment]
@yuecong do you know if the [`nodeLister`](https://github.com/m3db/m3db-operator/blob/f3b652c29e2e346b68ad60614d3becd5a90de35f/cmd/m3db-operator/main.go#L172) will still work fine even if the informer factory is scoped to a single namespace?

**Comment by yuecong** [comment]
@schallert yes, it does work. I tested in two environments in two different clouds.

From the code, `nodeLister` is used for `PodIdentityProvider`. And the controller will watch the pods and update pod identity to its pod name ( if it is default setting. Btw, I think this default setting is sufficient for most cases as it is already using sts for m3db nodes)

Maybe I miss something, if anything I need to test in my env, let me know.

**Comment by yuecong** [comment]
@schallert could you confirm whether this work for you when you have a chance to take a look? Thanks

**Comment by yuecong** [comment]
close this issue as https://github.com/m3db/m3db-operator/pull/205 is merged
