### ISSUE TITLE
Update contributing doc

### ISSUE THREAD

**Issue by EdgeJ** [m3db/m3db-operator#265]
The Contributing doc [mentions](https://github.com/m3db/m3db-operator/blame/master/CONTRIBUTING.md#L12) running `make dep-ensure`, but it looks like this make target no longer exists.  I'm not sure if there is an alternate command that needs to be run at this point.

* What happened?
```
~/git/misc/m3db-operator
➜ make dep-ensure
make: *** No rule to make target `dep-ensure'.  Stop.
```

**Comment by ChrisChinchilla** [comment]
@EdgeJ I encountered the same issue while rewriting the readme and contributor docs, `install-tools` seemed to work, though I am not sure if that's the **best** solution.
