### ISSUE TITLE
M3db instance creations fails

### ISSUE THREAD

**Issue by venkatram-velmurugan** [m3db/m3db-operator#292]
Below is the configuration of my kubernetes cluster setup

---
kubectl get nodes
NAME         STATUS   ROLES                  AGE   VERSION
bdx-master   Ready    control-plane,master   21d   v1.20.0
bdx-worker   Ready    <none>                 21d   v1.20.0

and the m3-operator and m3-cluster pod are up and running and versions are are v0.13.0 and v1.1.0 .

root@bdx-master:~# kubectl get pods -o wide
NAME                             READY   STATUS    RESTARTS   AGE     IP            NODE         NOMINATED NODE   READINESS GATES
etcd-0                           1/1     Running   0          5d20h   10.244.0.21   bdx-master   <none>           <none>
etcd-dqgvh5sfzt                  1/1     Running   0          5d20h   10.244.0.19   bdx-master   <none>           <none>
etcd-operator-6b6b84d9d6-fwv2d   1/1     Running   0          5d20h   10.244.0.18   bdx-master   <none>           <none>
m3db-cluster-rep0-0              1/1     Running   0          24h     10.244.0.65   bdx-master   <none>           <none>
m3db-operator-0                  1/1     Running   0          5d20h   10.244.0.20   bdx-master   <none>           <none>

Configmap file of m3-configuration:
----------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: m3-configuration
data:
  m3.yml: |+
    coordinator:
      listenAddress: 0.0.0.0:7201
      logging:
        level: info
      metrics:
        scope:
          prefix: "coordinator"
        prometheus:
          handlerPath: /metrics
          listenAddress: 0.0.0.0:7203
        sanitization: prometheus
        samplingRate: 1.0
        extended: none
      tagOptions:
        idScheme: quoted
      local:
        namespaces:
        - namespace: "collectd"
          type: unaggregated
          retention: 2h
    db:
      logging:
        level: info
      metrics:
        prometheus:
          handlerPath: /metrics
        sanitization: prometheus
        samplingRate: 1.0
        extended: detailed
      listenAddress: 0.0.0.0:9000
      clusterListenAddress: 0.0.0.0:9001
      httpNodeListenAddress: 0.0.0.0:9002
      httpClusterListenAddress: 0.0.0.0:9003
      debugListenAddress: 0.0.0.0:9004
      hostID:
        resolver: hostname
      client:
        writeConsistencyLevel: majority
        readConsistencyLevel: unstrict_majority
        writeTimeout: 10s
        fetchTimeout: 15s
        connectTimeout: 20s
        writeRetry:
            initialBackoff: 500ms
            backoffFactor: 3
            maxRetries: 2
            jitter: true
        fetchRetry:
            initialBackoff: 500ms
            backoffFactor: 2
            maxRetries: 3
            jitter: true
        backgroundHealthCheckFailLimit: 4
        backgroundHealthCheckFailThrottleFactor: 0.5

      gcPercentage: 100
      writeNewSeriesAsync: true
      writeNewSeriesBackoffDuration: 2ms
      commitlog:
        flushMaxBytes: 524288
        flushEvery: 1s
        queue:
          calculationType: fixed
          size: 2097152
      filesystem:
        filePathPrefix: /var/lib/m3db
      pooling:
        blockAllocSize: 16
        type: simple
        seriesPool:
            size: 262144
            lowWatermark: 0.7
            highWatermark: 1.0
        blockPool:
            size: 262144
            lowWatermark: 0.7
            highWatermark: 1.0
        encoderPool:
            size: 262144
            lowWatermark: 0.7
            highWatermark: 1.0
        closersPool:
            size: 104857
            lowWatermark: 0.7
            highWatermark: 1.0
        contextPool:
            size: 262144
            lowWatermark: 0.7
            highWatermark: 1.0
        segmentReaderPool:
            size: 16384
            lowWatermark: 0.7
            highWatermark: 1.0
        iteratorPool:
            size: 2048
            lowWatermark: 0.7
            highWatermark: 1.0
        fetchBlockMetadataResultsPool:
            size: 65536
            capacity: 32
            lowWatermark: 0.7
            highWatermark: 1.0
        fetchBlocksMetadataResultsPool:
            size: 32
            capacity: 4096
            lowWatermark: 0.7
            highWatermark: 1.0
        blockMetadataPool:
            size: 65536
            lowWatermark: 0.7
            highWatermark: 1.0
        blockMetadataSlicePool:
            size: 65536
            capacity: 32
            lowWatermark: 0.7
            highWatermark: 1.0
        blocksMetadataPool:
            size: 65536
            lowWatermark: 0.7
            highWatermark: 1.0
        blocksMetadataSlicePool:
            size: 32
            capacity: 4096
            lowWatermark: 0.7
            highWatermark: 1.0
        identifierPool:
            size: 262144
            lowWatermark: 0.7
            highWatermark: 1.0
        bytesPool:
            buckets:
                - capacity: 16
                  size: 524288
                  lowWatermark: 0.7
                  highWatermark: 1.0
                - capacity: 32
                  size: 262144
                  lowWatermark: 0.7
                  highWatermark: 1.0
                - capacity: 64
                  size: 131072
                  lowWatermark: 0.7
                  highWatermark: 1.0
                - capacity: 128
                  size: 65536
                  lowWatermark: 0.7
                  highWatermark: 1.0
                - capacity: 256
                  size: 65536
                  lowWatermark: 0.7
                  highWatermark: 1.0
                - capacity: 1440
                  size: 16384
                  lowWatermark: 0.7
                  highWatermark: 1.0
                - capacity: 4096
                  size: 8192
                  lowWatermark: 0.7
                  highWatermark: 1.0
      discovery:
        config:
          service:
              env: default_env
              zone: embedded
              service: m3db
              cacheDir: /var/lib/m3kv
              etcdClusters:
              - zone: embedded
                endpoints:
                - http://etcd-0.etcd:2379
                
and below is m3db-cluster yaml file and provided replicationFactor is 1 and numberofShared is 16.

single-cluster.yaml
----------------------
apiVersion: operator.m3db.io/v1alpha1
kind: M3DBCluster
metadata:
  name: m3db-cluster
spec:
  image: quay.io/m3db/m3dbnode:latest
  imagePullPolicy: IfNotPresent
  replicationFactor: 1
  numberOfShards: 16
  namespaces:
    - name: collectd
      options:
        bootstrapEnabled: true
        flushEnabled: true
        writesToCommitLog: true
        cleanupEnabled: true
        snapshotEnabled: true
        repairEnabled: false
        retentionOptions:
            retentionPeriod: 2h
            blockSize: 1h
            bufferFuture: 5m
            bufferPast: 5m
            blockDataExpiry: true
            blockDataExpiryAfterNotAccessPeriod: 2m
        indexOptions:
            enabled: true
            blockSize: 2h
  etcdEndpoints:
  - http://etcd-0.etcd:2379
  isolationGroups:
  - name: group1
    numInstances: 1
    nodeAffinityTerms:
       - key: failure-domain.beta.kubernetes.io/zone
         values:
             - us-west1-a
  podIdentityConfig:
    sources:
      - PodUID
  configMapName: m3-configuration
  namespaces:
    - name: collectd
      preset: 10s:2d

After deployed the m3db-cluster in my server, I am not able to create the instance and its throwing error 
curl -X POST http://localhost:7201/api/v1/services/m3db/namespace/ready -d '{"name": "default"}' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    97  100    78  100    19  39000   9500 --:--:-- --:--:-- --:--:-- 48500
{
  "status": "error",
  "error": "could not find db session for namespace: default"
}

even after created 24 hrs, its  "state": "INITIALIZING", but the retentionPeriod configured as 2h and numberofShared as 16. 
{
  "placement": {
    "instances": {
      "m3db_local": {
        "id": "m3db_local",
        "isolationGroup": "local",
        "zone": "embedded",
        "weight": 1,
        "endpoint": "127.0.0.1:9000",
        "shards": [
          {
            "id": 0,
            "state": "INITIALIZING",
            "sourceId": "",
            "cutoverNanos": "0",
            "cutoffNanos": "0"
          },
          {
            "id": 1,
            "state": "INITIALIZING",
            "sourceId": "",
            "cutoverNanos": "0",
            "cutoffNanos": "0"
          },
          .......
          {
            "id": 63,
            "state": "INITIALIZING",
            "sourceId": "",
            "cutoverNanos": "0",
            "cutoffNanos": "0"
          },
          ]
          "shardSetId": 0,
	          "hostname": "localhost",
	          "port": 9000,
	          "metadata": {
	            "debugPort": 0
	          }
	        }
	      },
	      "replicaFactor": 1,
	      "numShards": 64,
	      "isSharded": true,
	      "cutoverTime": "0",
	      "isMirrored": false,
	      "maxShardSetId": 0
	    },
	    "version": 1
	  }
It will be nice to provide some suggestions/solutions for this?

**Comment by wesleyk** [comment]
@venkatram-velmurugan looks like the namespace you have created is called `collectd`. You'll want to pass that in for the API call to ready the namespace:

```
curl -X POST http://localhost:7201/api/v1/services/m3db/namespace/ready -d '{"name": "collectd"}' | jq .
```
