### ISSUE TITLE
Missing "patch" permission for ClusterRole

### ISSUE THREAD

**Issue by skupjoe** [m3db/m3db-operator#296]
While completing the final steps of [Creating a Cluster](https://operator.m3db.io/getting_started/create_cluster/) & verifying, I see that m3db resources are deployed, but the bootstrapping process process fails.

```
$ kubectl -n monitoring exec m3db-cluster-rep2-0 -- curl -sSf localhost:9002/health
{"ok":true,"status":"up","bootstrapped":false}
```

I am seeing the following error logged by m3db-operator:
```
error syncing cluster 'monitoring/m3db-cluster': configmaps "m3db-config-map-m3db-cluster" is forbidden: User "system:serviceaccount:monitoring:m3db-operator" cannot patch resource "configmaps" in API group "" in the namespace "monitoring"
{"level":"info","ts":1626390158.5154006,"msg":"Event(v1.ObjectReference{Kind:\"M3DBCluster\", Namespace:\"monitoring\", Name:\"m3db-cluster\", UID:\"6ed328aa-307d-401f-a980-843c4c1fcb66\", APIVersion:\"operator.m3db.io/v1alpha1\", ResourceVersion:\"138139500\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedToSync' failed to ensure configmap: configmaps \"m3db-config-map-m3db-cluster\" is forbidden: User \"system:serviceaccount:monitoring:m3db-operator\" cannot patch resource \"configmaps\" in API group \"\" in the namespace \"monitoring\"","controller":"m3db-cluster-controller"}
```
![image](https://user-images.githubusercontent.com/5000412/126446705-636eaa23-f2e0-47aa-92ba-bd4c06cac9b2.png)

**To fix the issue, I needed to modify the `m3db-operator`  ClusterRole and add the `patch` role to the rule `persistentvolumes, persistentvolumeclaims, services, secrets, configmaps`.**

Operator version:
`quay.io/m3db/m3db-operator:v0.12.0 (latest)`

m3dbnode version:
`quay.io/m3db/m3dbnode:v1.1.0 (255a4b14d)`

etcd version:
`quay.io/coreos/etcd:v3.5.0 (latest)`

Kubernetes version:
`GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8"`

**Comment by gibbscullen** [comment]
@skupjoe .. following up on #295, this issue could be related to the config you're using so would be helpful to know where you found it.

**Comment by skupjoe** [comment]
Hi @gibbscullen this is all using the default operator/config. The operator creates all the necessary resources, ClusterRoles, etc automatically and I haven't modified this. I just simply was following your [operator docs](https://m3db.io/docs/operator/getting_started/).
