### ISSUE TITLE
Will there be a new release soon ?

### ISSUE THREAD

**Issue by abdulmi** [m3db/m3db-operator#319]
Hi, will there be a new release cut anytime soon? It seems that the latest release was cut from Feb 2021 https://github.com/m3db/m3db-operator/commits/v0.13.0, which is more than a year ago. There are some useful features that were merged into master since then that we'd love to use.

Cheers!

**Comment by schallert** [comment]
v0.14.0 is out! https://github.com/m3db/m3db-operator/releases/tag/v0.14.0
