### ISSUE TITLE
Ensure data in etcd is cleared on cluster deletion

### ISSUE THREAD

**Issue by schallert** [m3db/m3db-operator#44]
Potentially using a finalizer or similar method to hook into cluster deletion

**Comment by prateek** [comment]
Try not to use the go `SetFinalizer` call as far as you can. It has really weird guarantees that are best avoided.

**Comment by schallert** [comment]
Ah, I meant finalizer in the context of a [Kubernetes finalizer](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion)

**Comment by prateek** [comment]
👍 dope, just wanted to make sure
